### ISSUE TITLE
PIR sensor Interfacing

### ISSUE THREAD

**Issue by mikeshams** [Shahrukh-padaniya/CapstoneProject_G6#10]
Explain about single mode triggering of a PIR sensor

**Comment by Swapnil-007** [comment]
The jumper setting on the PIR sensor must be set to LOW to choose Single Trigger mode. When motion is detected in Single Triggered Mode, The output becomes HIGH. Even if the item is moving, the output switches to LOW after a defined delay (tsel).
If the item stays in motion, the output is LOW for a while before returning to HIGH. The user controls the delay (tsel) with the potentiometer. This potentiometer is located on the PIR sensor module's PCB. If the item is moving continuously, the PIR sensor will emit HIGH/LOW pulses.
