### ISSUE TITLE
GSM Module Interfacing

### ISSUE THREAD

**Issue by mikeshams** [Shahrukh-padaniya/CapstoneProject_G6#11]
Demonstrate the interfacing! What was the issue preventing doing the task in time?

**Comment by Shahrukh-padaniya** [comment]
Initially, we did not check which service provider uses GSM bands supported for sim868, but after checking we got to know that we can use fido or rogers. So we used rogers and it is working fine for making calls and sending messages.

**Comment by Shahrukh-padaniya** [comment]
We have ordered fido sim card online. It will take 3-5 days to deliver at my home address. We ordered online as to save 45 $ activation fees.

**Comment by Shahrukh-padaniya** [comment]
The fido SIMcard will be delivered by today. (monday, july, 19th)
