### ISSUE TITLE
Speaker Interfacing

### ISSUE THREAD

**Issue by mikeshams** [Shahrukh-padaniya/CapstoneProject_G6#12]
Is there a viable solution for controlling the music type and its volume by the general end user?

**Comment by vandana-embt** [comment]
yes sir we are trying to use a web page where the end-user can access through the music type and controlling music. We are working on it sir as soon as we are done will inform you, sir.

**Comment by vandana-embt** [comment]
sir can you give us more time to complete the task we are working on it.

**Comment by vandana-embt** [comment]
got the output sir, will demonstrate in the next class.
