### ISSUE TITLE
PCB Layout Design

### ISSUE THREAD

**Issue by mikeshams** [Shahrukh-padaniya/CapstoneProject_G6#13]
1. What is a gerber file?
2. What is DRC?
3. What to do if we can not find the foot print for one component?

**Comment by Swapnil-007** [comment]
1. What is a gerber file?
Gerber files are ASCII vector files in which each physical board layer of your PCB design is described. Copper traces, vias, pads, solder masks, and silkscreen pictures are all represented on a circuit board by a flash or draw code and specified by a set of vector coordinates. PCB manufacturers utilize these files to transform the specifics of your design into the physical characteristics of the board.

2. What is DRC?
A design rule check (DRC) is a collection of criteria that a designer may employ to guarantee that their schematic fits all of the board's dimensional tolerances and manufacturing concerns. Variation is an inherent component of every manufacturing process.

3. What to do if we can not find the foot print for one component?
If we didn't find the footprint for any component than we can add it through footprint manager. In windows OS all the footprint libraries were installed during the time of installation. But, if we want to use it in Ubuntu than we need to install the footprint library separately using some codes in ubuntu terminal.
