### ISSUE TITLE
Demonstration

### ISSUE THREAD

**Issue by mikeshams** [Shahrukh-padaniya/CapstoneProject_G6#2]
1) Show the remaining components
2) Test them in class

**Comment by Shahrukh-padaniya** [comment]
Some of our components will be delivered by 22nd june 2021. I will demonstrate on testing components which we have on Thursday, June 17th.

**Comment by Shahrukh-padaniya** [comment]
We got all our components and tested successfully expect pulse oximeter and speaker, which we are going to receive on 22nd june 2021.

**Comment by mikeshams** [comment]
PLease modify test them asap!

**Comment by Shahrukh-padaniya** [comment]
We are about to get our remaining 2 components on 22nd June as scheduled earlier. I will test them as soon as possible.

**Comment by mikeshams** [comment]
I have updated the milestone.

**Comment by Rohan-yadav** [comment]
I have just received pulse oximeter but i have to go to work for nightshift so can i demonstrate on thursday for pulse oximeter interfacing?

**Comment by Rohan-yadav** [comment]
Now we have all the components we need.

**Comment by Shahrukh-padaniya** [comment]
We have received all the hardware components and tested them successfully. (USB speaker and pulse oximeter). I can demonstrate today.

**Comment by mikeshams** [comment]
noted.
