### ISSUE TITLE
Raspberry Pi Setting Up

### ISSUE THREAD

**Issue by mikeshams** [Shahrukh-padaniya/CapstoneProject_G6#4]
Add titles to all slides and have your references in APA format for the ppt file

**Comment by Swapnil-007** [comment]
sure sir. I did all the changes as you say . And here I attach corrected PPT.
thank you.
[Raspberry pi interfacing.pptx](https://github.com/Shahrukh-padaniya/CapstoneProject_G6/files/6703827/Raspberry.pi.interfacing.pptx)

**Comment by mikeshams** [comment]
Modify your references!

**Comment by Swapnil-007** [comment]
Sure sir . I modified the references and here I attached PPT with corrections.
[Raspberry pi interfacing.pptx](https://github.com/Shahrukh-padaniya/CapstoneProject_G6/files/6735786/Raspberry.pi.interfacing.pptx)
