### ISSUE TITLE
Testing Components (2)

### ISSUE THREAD

**Issue by mikeshams** [Shahrukh-padaniya/CapstoneProject_G6#5]
Review the interfacing code for the Humidity/ Temperature sensor and add comments line by line

**Comment by Shahrukh-padaniya** [comment]
I have updated the code for humidity and temperature sensor and also added the comments to understand easier. You can also find the commented code below;

#include <dht.h>​
#define PIN7// sensor is connected to pin 7 of Arduino​
dht DHT;​
void setup(){                               //start setup​
Serial.begin(9600);​
delay(500);                               //Delay to let system boot​
Serial.println("DHT11 Humidity & temperature Sensor\n\n");​
delay(1000);                           //Wait before accessing Sensor​
}                                                  //end "setup()"​
void loop(){                              //Start of Program ​
DHT.read11(dht_apin);​
Serial.print("Current humidity = ");​
Serial.print(DHT.humidity);     //print humidity in percentage​
Serial.print("%  ");​
Serial.print("temperature = ");​
Serial.print(DHT.temperature);    //print temperature in C​
Serial.println("C  ");​
delay(5000);                   //Wait 5 seconds before accessing the sensor again.​
}                                           // end loop
