### ISSUE TITLE
Pulse Oximeter Interfacing

### ISSUE THREAD

**Issue by mikeshams** [Shahrukh-padaniya/CapstoneProject_G6#8]
Convert your code into C/ C++

**Comment by Rohan-yadav** [comment]
I have solved the issue.

**Comment by mikeshams** [comment]
Demonstrate it on Monday July 12 !

**Comment by Rohan-yadav** [comment]
I updated ppt file [https://github.com/Shahrukh-padaniya/CapstoneProject_G6/blob/main/Pulse-oximeterTopi.pptx](url)
