### ISSUE TITLE
Humidity & Temperature Sensor Interfacing

### ISSUE THREAD

**Issue by mikeshams** [Shahrukh-padaniya/CapstoneProject_G6#9]
1. How to change humidity without changing the temperature?
2. Demonstrate this task

**Comment by vandana-embt** [comment]
We can change humidity without changing temperature in two ways
1.If the humidity gets too high we can achieve this without cooling the rooms too much, use an air exchanger: a heat recovery ventilator (HRV) or energy-recovery ventilator (ERV) or dehumidifier.
Conversely, if the humidity is too low, a portable humidifier or one connected to a central forced-air heating system is an effective solution.
2.We did not receive the component yet sir as soon as we receive it I will be ready to demonstrate it, sir.

**Comment by vandana-embt** [comment]
Sir got the DHT11 component and I am ready to demonstrate the task
